/**
 * Contexte de langue pour l'internationalisation de DuoClass
 * Gère le changement de langue français/anglais
 */
import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traductions françaises
const fr: Record<string, string> = {
  // Header
  'app.title': 'DuoClass',
  'app.subtitle': 'La gestion de vos photos et documents maîtrisée',
  'header.admin': 'ADMIN',
  'header.avatar': 'Avatar',
  'header.language': 'FR',
  
  // Trial Banner
  'trial.period': 'Période d\'essai',
  'trial.daysRemaining': 'jour restant',
  'trial.daysRemainingPlural': 'jours restants',
  'trial.photosRemaining': 'photos restantes',
  'trial.subscribe': 'S\'abonner',
  
  // Toolbar
  'toolbar.display': 'Affichage',
  'toolbar.normal': 'Normal',
  'toolbar.size': 'Taille',
  'toolbar.import': 'Importer',
  'toolbar.add': 'Ajouter',
  'toolbar.delete': 'Supprimer',
  'toolbar.photoEdit': 'Retouches Photos',
  'toolbar.convert': 'Convertir',
  'toolbar.email': '@Mail',
  'toolbar.print': 'Imprimer',
'toolbar.slideshow': 'Diaporama',
   'toolbar.creations': 'Atelier',
   'toolbar.photoBook': 'Livre Photo',
   
   // Sidebar
  'sidebar.discovery': 'Découverte',
  'sidebar.albums': 'Albums',
  'sidebar.privateAlbums': 'Albums Privés',
  'sidebar.settings': 'Paramètres',
  'sidebar.themes': 'Thèmes\nInterface',
  'sidebar.help': 'Aide',
  'sidebar.utilities': 'Utilitaires',
  
  // Pages
  'page.home': 'Accueil',
  'page.albums': 'Albums',
  'page.privateAlbums': 'Albums Privés',
  'page.settings': 'Paramètres',
  'page.themes': 'Thèmes',
  'page.help': 'Aide',
  'page.discovery': 'Découverte',
  'page.photoEdit': 'Retouche Photo',
  'page.helpDocs': 'Aide & Documentation',
  
  // Albums
  'albums.title': 'Albums',
  'albums.photosVideos': 'Photos & Vidéos',
  'albums.creations': 'Créations',
  'albums.documents': 'Documents',
  'albums.categories': 'Catégories',
  'albums.createCategory': 'Créer catégorie/album',
  'albums.notClassified': 'NON CLASSEE',
  'albums.notClassifiedAlbums': 'Non classées',
  'albums.deleteCategory': 'Supprimer cette catégorie',
  'albums.deleteAlbum': 'Supprimer cet album',
  'albums.renameAlbum': "Renommer l'album",
  'albums.enterNewName': 'Entrez le nouveau nom',
  'albums.newName': 'Nouveau nom',
  'albums.confirmDelete': 'Confirmer la suppression',
  'albums.cancel': 'Annuler',
  'albums.delete': 'Supprimer',
  'albums.noCategory': 'Aucune catégorie',
  'albums.noAlbum': 'Aucun album',
  'albums.returnToAlbums': 'Retour aux Albums',
  'albums.password4digits': 'Mot de passe (4 chiffres)',
  'albums.protectedCategory': 'Catégorie protégée',
  'albums.categoryProtectedMsg': 'La catégorie {category} est protégée par un mot de passe.',
  'albums.confirmDeleteCategory': 'Êtes-vous sûr de vouloir supprimer la catégorie "{category}" ?',
  'albums.confirmDeleteAlbum': 'Êtes-vous sûr de vouloir supprimer l\'album "{album}" ?',
  'albums.allAlbumsWillBeDeleted': 'Tous les albums de cette catégorie seront également supprimés.',
  'albums.dragToMove': 'Glissez pour déplacer vers une autre catégorie',
  
  // Albums Privés
  'privateAlbums.title': 'Albums Privés',
  'privateAlbums.enterMasterCode': 'Entrez le Code Maître pour accéder aux albums privés',
  'privateAlbums.masterCode': 'Code Maître',
  'privateAlbums.masterCodePlaceholder': 'Code Maître (ex: 000000)',
  'privateAlbums.unlock': 'Déverrouiller',
  'privateAlbums.hidden': 'Masqué',
  
  // PhotoClass / UniversalAlbumPage
  'photoclass.title': 'PhotoClass',
  'photoclass.accessType': 'Type d\'accès',
  'photoclass.photos': 'PHOTOS',
  'photoclass.documents': 'DOCUMENTS',
  'photoclass.category': 'Catégorie',
  'photoclass.album': 'Album',
  'photoclass.images': 'Images',
  'photoclass.returnAlbums': 'Retour Albums',
  'photoclass.deleteAlbum': 'Supprimer l\'album',
  'photoclass.dropPhotosHere': 'Déposez vos photos ici',
  'photoclass.dropDocsHere': 'Déposez vos documents ici',
  'photoclass.framesCreatedAuto': 'Les cadres seront créés automatiquement',
  'photoclass.goToTop': 'Aller en haut de l\'album',
  'photoclass.goUp25': 'Remonter de 25 photos',
  'photoclass.goDown25': 'Descendre de 25 photos',
  'photoclass.goToEnd': 'Aller à la fin de l\'album',
  'photoclass.notClassified': 'Non classée',
  'photoclass.imageLimitedResolution': 'La grandeur de l\'image est limitée en raison de la faible résolution de l\'image',
  
  // Frame Management
  'frames.management': 'Gestion des cadres',
  'frames.count': 'Nombre de cadres :',
  'frames.addBefore': 'Ajouter AVANT',
  'frames.addAfter': 'Ajouter APRÈS',
  'frames.deleteEmpty': 'Supprimer tous les cadres vides',
  'frames.deleteThis': 'Supprimer ce cadre',
  'frames.confirmDelete': 'Confirmer la suppression',
  'frames.containsPhoto': 'Ce cadre contient une photo.',
  'frames.containsDoc': 'Ce cadre contient un document.',
  'frames.confirmDeleteQuestion': 'Voulez-vous vraiment supprimer ce cadre ?',
  'frames.emptyFrame': 'Vider le cadre',
  'frames.confirmEmptyQuestion': 'Voulez-vous vraiment vider ce cadre ?',
  
  // Details Modal
  'details.photoDetails': 'Détails de la photo',
  'details.docDetails': 'Détails du document',
  'details.title': 'Titre',
  'details.format': 'Format',
  'details.date': 'Date',
  'details.location': 'Lieu / Origine',
  'details.comments': 'Commentaires / Notes',
  
  // Export Modal
  'export.allowDownload': 'Votre navigateur va vous demander d\'autoriser le téléchargement. Cliquez sur "Autoriser" pour continuer.',
  'export.whereFiles': 'Où vont vos fichiers ?',
  'export.toDesktop': 'Pour que vos fichiers arrivent directement sur le Bureau, vous pouvez modifier les paramètres de votre navigateur :',
  'export.safariSettings': 'Safari : Préférences → Général → Emplacement de téléchargement → Bureau',
  'export.chromeSettings': 'Chrome : Paramètres → Téléchargements → Modifier → Bureau',
  'export.dontShowAgain': 'Ne plus afficher ce message',
  'export.continue': 'Continuer',
  
  // Convert Modal
  'convert.title': 'Convertir les éléments',
  'convert.pdfFormat': 'Format PDF',
  'convert.pdfDesc': 'Fusionner en un seul document',
  'convert.imagesFormat': 'Format Images (ZIP)',
  'convert.imagesDesc': 'Extraire en fichiers séparés',
  'convert.outputFormat': 'Format de sortie :',
  
  // Import Modal
  'import.title': 'Importer des fichiers depuis...',
  'import.camera': 'Caméra',
  'import.takePhoto': 'Prendre une photo',
  'import.fileManager': 'Gestionnaire',
  'import.fileManagerDesc': 'de fichiers',
  'import.windowsLinux': 'Windows / Linux',
  'import.finder': 'Finder',
  'import.macos': 'macOS',
  
  // Camera Modal
  'camera.title': 'Prendre une photo',
  'camera.capture': 'Capturer',
  
  // Delete Album
  'deleteAlbum.title': 'Supprimer l\'album',
  'deleteAlbum.password': 'Mot de passe',
  'deleteAlbum.passwordRequired': 'Mot de passe requis',
  'deleteAlbum.deleteForever': 'Supprimer définitivement',
  
  // Move Elements
  'move.title': 'Déplacer les éléments',
  'move.moveElements': 'Déplacer {count} élément(s) :',
  'move.noOtherAlbum': 'Aucun autre album disponible',
  'move.createFirst': 'Créez d\'abord un autre album dans {type}',
  'move.selectDestination': 'Sélectionnez l\'album de destination :',
  
  // Paramètres
  'settings.title': 'Paramètres',
  'settings.personalInfo': 'Informations Personnelles',
  'settings.lastName': 'Nom',
  'settings.firstName': 'Prénom',
  'settings.address': 'Adresse',
  'settings.email': 'Email',
  'settings.phone': 'N° Portable',
  'settings.yourLastName': 'Votre nom',
  'settings.yourFirstName': 'Votre prénom',
  'settings.yourAddress': 'Votre adresse complète',
  'settings.startPage': 'Page au démarrage',
  'settings.chooseStartPage': 'Choisissez la page qui s\'affiche à l\'ouverture de l\'application :',
  'settings.home': 'Accueil (Hub)',
  'settings.photoLibrary': 'Photothèque PhotoClass',
  'settings.discovery': 'Page Découverte',
  'settings.wantAvatar': 'Souhaitez-vous avoir un avatar ?',
  'settings.chooseImage': 'Choisir une image',
  'settings.findAvatarPixabay': 'Trouvez votre avatar parfait sur Pixabay',
  'settings.orUploadPhoto': 'Ou téléchargez votre photo',
  'settings.useChooseImage': 'Utiliser la fonction : choisir une image',
  'settings.removeAvatar': 'Supprimer l\'avatar',
  'settings.masterCode': 'Code Maître',
  'settings.currentCode': 'Code actuel',
  'settings.newCode': 'Nouveau code',
  'settings.confirmCode': 'Confirmer le code',
  'settings.min4chars': 'Minimum 4 caractères',
  'settings.repeatCode': 'Répétez le code',
  'settings.updateCode': 'Mettre à jour le code',
  'settings.sessionDisconnect': 'Session & Déconnexion',
  'settings.inactivityDelay': 'Délai d\'inactivité (minutes)',
  'settings.recommended': 'Recommandé',
  'settings.minutes': 'minutes',
  'settings.hour': 'heure',
  'settings.noDisconnectTimeRange': 'Plage horaire sans déconnexion (Ex: Bureau)',
  'settings.to': 'à',
  'settings.saveSessionSettings': 'Enregistrer les réglages session',
  'settings.parentalControl': 'Contrôle Parental',
  'settings.aiAnalysis': 'L\'Intelligence Artificielle analyse et bloque automatiquement les contenus sensibles lors de l\'importation.',
  'settings.disabled': 'Désactivé',
  'settings.moderate': 'Modéré',
  'settings.strict': 'Strict',
  'settings.veryStrict': 'Très Strict (Niveau 5)',
  'settings.currentLevel': 'Niveau actuel',
  'settings.level5Desc': 'Le niveau 5 bloque toute nudité, violence ou contenu inapproprié avec une tolérance zéro.',
  'settings.backupRecovery': 'Sauvegarde et Récupération',
  'settings.createBackup': 'Créer une sauvegarde',
  'settings.downloadAlbums': 'Téléchargez tous vos albums et réglages',
  'settings.download': 'Télécharger',
  'settings.restoreBackup': 'Restaurer une sauvegarde',
  'settings.importBackupFile': 'Importer un fichier de sauvegarde',
  'settings.import': 'Importer',
  'settings.autoBackup': 'Sauvegarde automatique',
  'settings.scheduleBackups': 'Programmez des sauvegardes régulières',
  'settings.day': 'Jour',
  'settings.week': 'Semaine',
  'settings.month': 'Mois',
  'settings.cleanCategories': 'Nettoyer les catégories',
  'settings.deleteUnused': 'Supprimer les catégories inutilisées',
  'settings.clean': 'Nettoyer',
  'settings.factoryReset': 'Réinitialisation d\'usine',
  'settings.resetDesc': 'Remet l\'application à zéro : supprime toutes les données.',
  'settings.irreversible': 'Irréversible !',
  'settings.reset': 'Réinitialiser',
  'settings.legalInfo': 'Informations Légales & Support',
  'settings.termsOfUse': 'Conditions Générales d\'Utilisation (CGU)',
  'settings.legalNotice': 'Mentions Légales',
  'settings.privacyPolicy': 'Politique de Confidentialité',
  'settings.perpetualLicense': 'Licence Perpétuelle (À vie)',
  'settings.needHelp': 'Besoin d\'aide ?',
  'settings.supportAvailable': 'Notre équipe de support est disponible pour vous aider.',
  'settings.contactSupport': 'Contacter le support technique',
  'settings.myLicenses': 'Mes Licences',
  'settings.myLicensesDesc': 'Gérez vos licences DuoClass, activez de nouveaux codes et transférez vos licences entre appareils.',
  'settings.manageLicenses': 'Gérer mes licences',
  'settings.accessDenied': 'Accès autorisé',
  'settings.wrongCode': 'Code incorrect',
  'settings.protectedAccess': 'Accès Protégé',
  'settings.enterMasterCode': 'Entrez le Code Maître pour accéder aux paramètres',
  'settings.masterCodePlaceholder': 'Code maître...', 'settings.general': 'Général',
  'settings.personalization': 'Personnalisation',
  'settings.security': 'Sécurité',
  'settings.backups': 'Sauvegardes',
  'settings.infosLicense': 'Infos & Licence',
  'settings.file': 'Fichier :',
  'settings.backupDate': 'Date de sauvegarde :',
  'settings.albumsCount': 'Albums :',
  'settings.categoriesCount': 'Catégories :',
  'settings.settingsIncluded': 'Paramètres :',
  'settings.importMode': 'Mode d\'importation :',
  'settings.merge': 'Fusionner',
  'settings.replace': 'Remplacer',
  'settings.replaceWarning': 'Attention : Le mode "Remplacer" supprimera tous vos albums et catégories actuels avant d\'importer la sauvegarde. Cette action est irréversible.',
  'settings.allDataDeleted': 'Toutes les données seront supprimées :',
  'settings.allCategories': 'Toutes les catégories',
  'settings.allAlbums': 'Tous les albums',
  'settings.allPhotosAndDocs': 'Toutes les photos et documents',
  'settings.allCustomSettings': 'Tous les réglages personnalisés',
  'settings.appResetToInitial': 'L\'application reviendra à son état initial (comme au premier lancement).',
  'settings.typeToConfirm': 'Pour confirmer, tapez',
  'settings.resetKeyword': 'REINITIALISER',
  'settings.typeResetPlaceholder': 'Tapez REINITIALISER',
  'settings.restrictedAccess': 'Accès Réservé',
  'settings.sectionReserved': 'Cette section est réservée à l\'administrateur.',
  'settings.masterCodeDesc': 'Ce code protège l\'accès à cette page Administration, aux albums sécurisés et aux fonctions sensibles.',
  'settings.emailPlaceholder': 'votre@email.com',
  'settings.phonePlaceholder': '06...',
  'settings.verifyBeforeImport': 'Vérifiez les informations du fichier avant de procéder à l\'import.',
  'settings.mergeDesc': 'Ajoute les nouveaux albums sans écraser les existants',
  'settings.replaceDesc': 'Supprime tout et restaure depuis la sauvegarde',
  'settings.importing': 'Import en cours...',
  'settings.replaceAll': 'Remplacer tout',
  'settings.warningIrreversible': 'ATTENTION : Cette action est irréversible !',
  'settings.resetting': 'Réinitialisation...',
  'settings.confirmReset': 'Confirmer la réinitialisation',
  
  // Themes
  'themes.title': 'Thèmes de l\'interface',
  'themes.reset': 'Réinitialiser',
  'themes.apply': 'Appliquer',
  'themes.colors': 'Couleurs',
  'themes.texture': 'Texture extérieure',
  'themes.workarea': 'Fond zone de travail',
  'themes.saveConfig': 'Sauvegarder la configuration actuelle',
  'themes.configNamePlaceholder': 'Nom de la configuration (ex: Mon thème bureau)',
  'themes.mySavedConfigs': 'Mes configurations sauvegardées',
  'themes.classic': 'Classique',
  'themes.starryNight': 'Nuit Étoilée',
  'themes.nordic': 'Nordique',
  'themes.forest': 'Forêt',
  'themes.ocean': 'Océan',
  'themes.sunset': 'Soleil',
  'themes.lavender': 'Lavande',
  'themes.graphite': 'Graphite',
  'themes.rose': 'Rose',
  'themes.midnightGold': 'Minuit Doré',
  'themes.none': 'Aucune',
  'themes.brownLeather': 'Cuir Marron',
  'themes.crocoLeather': 'Cuir Croco',
  'themes.moireBlue': 'Moiré Bleu',
  'themes.moireGreen': 'Moiré Vert',
  'themes.moireRed': 'Moiré Rouge',
  'themes.moirePink': 'Moiré Rose',
  'themes.marbleBlue': 'Marbre Bleu',
  'themes.marbleBeige': 'Marbre Beige',
  'themes.rustedMetal': 'Métal Rouillé',
  'themes.gold': 'Or',
  'themes.bamboo': 'Bambou',
  'themes.flames': 'Flammes',
  'themes.transparent': 'Transparent',
  'themes.white': 'Blanc',
  'themes.sand': 'Sable',
  'themes.cream': 'Crème',
  'themes.ivory': 'Ivoire',
  'themes.pastelBlue': 'Bleu',
  'themes.pastelGreen': 'Vert',
  'themes.pastelPink': 'Rose',
  'themes.pastelLavender': 'Lavande',
  'themes.pastelPeach': 'Pêche',
  'themes.gray': 'Gris',
  'themes.myConfigs': 'Mes configurations',
  'themes.save': 'Sauver',
  'themes.applyConfig': 'Appliquer',
  'themes.noConfigs': 'Aucune configuration sauvegardée. Personnalisez votre thème puis cliquez sur "Sauver cette configuration".',
  'themes.currentConfig': 'Configuration actuelle',
  'themes.enterConfigName': 'Veuillez entrer un nom pour cette configuration',
  'themes.configSaved': 'Configuration sauvegardée !',
  'themes.configApplied': 'Configuration appliquée !',
  'themes.configDeleted': 'Configuration supprimée',
  
  // Retouche Photo
  'photoEdit.title': 'Retouche Photo',
  'photoEdit.originalPhoto': 'Photo originale',
  'photoEdit.editedPhoto': 'Photo retouchée',
  'photoEdit.noPhoto': 'Aucune photo',
  'photoEdit.doubleClickZoom': 'Double-clic pour agrandir',
  'photoEdit.titlePlaceholder': 'Titre',
  'photoEdit.commentsPlaceholder': 'Commentaires',
  'photoEdit.selectedInPhotoclass': 'Photo sélectionnée dans PhotoClass',
  'photoEdit.editedWillAppear': 'La photo retouchée apparaîtra ici',
  'photoEdit.newEdit': 'Nouvelle retouche',
  'photoEdit.saveAsCopy': 'Enregistrer comme copie dans l\'album',
  
  // Help / Utilitaires
  'help.title': 'Aide',
  'help.docCenter': 'Centre de Documentation',
  'help.techSupport': 'Assistance technique :',
  'help.adminInfosLicense': 'Administration > Infos & Licence',
  'help.didYouKnow': 'Le saviez-vous ?',
  'help.contextualHelp': 'Accédez à l\'aide contextuelle en cliquant sur le bouton "Pouce" 👍 dans la barre supérieure.',
  'help.welcome': 'Bienvenue dans l\'aide de DuoClass',
  'help.description': 'DuoClass est votre application de gestion de photos et documents.',
  'help.duplicateValidation': 'Validation des Doublons',
  'help.duplicateDesc': 'Gérer les photos détectées comme doublons.',
  'help.manage': 'Gérer',
  'help.quickStart': 'Guide Démarrage Rapide',
  'help.quickStartDesc': 'L\'essentiel pour commencer.',
  'help.view': 'Voir',
  'help.userManual': 'Manuel Utilisateur',
  'help.userManualDesc': 'Toutes les fonctionnalités (PDF).',
  'help.read': 'Lire',
  'help.shortcuts': 'Raccourcis Clavier',
  'help.shortcutsDesc': 'Tous les raccourcis pour aller plus vite.',
  'help.techSupportTitle': 'Support Technique',
  'help.techSupportDesc': 'Contactez notre équipe.',
  
  // WorkSpace
  'workspace.title': 'Surface de Travail',
  'workspace.emptyZone': 'Zone de travail vide',
  'workspace.dragItems': 'Glissez des éléments ici ou utilisez la barre d\'outils',
  
  // Home / Landing
  'home.adminMode': 'Attention, vous êtes en mode "Administrateur", n\'oubliez pas de revenir en libre',
  'home.confirmQuit': 'Êtes-vous sûr de vouloir quitter ?',
  'home.secureAlbum': 'Album Sécurisé',
  'home.enterMasterCode': 'Veuillez entrer votre Code Maître pour accéder à cet album.',
  'home.validate': 'Valider',
  'home.deleteAlbum': 'Supprimer l\'album',
  'home.masterCodeRequired': 'Code Maître requis :',
  
  // Landing Page
  'landing.title': 'DuoClass',
  'landing.subtitle': 'La gestion de vos photos et documents maîtrisée',
  'landing.startFree': 'Commencer gratuitement',
  'landing.login': 'Se connecter',
  'landing.freeTrial': 'Essai gratuit',
  'landing.intuitiveInterface': 'Une interface intuitive',
  'landing.discoverApp': 'Découvrez l\'application DuoClass en action',
  'landing.organizeMedia': 'Organisez vos médias',
  'landing.classifyDocs': 'Classez vos papiers',
  'landing.secure': 'Sécurisé',
  'landing.privateAlbums': 'Albums privés',
  'landing.product': 'Produit',
  'landing.features': 'Fonctionnalités',
  'landing.pricing': 'Tarifs',
  'landing.updates': 'Mises à jour',
  'landing.support': 'Support',
  'landing.helpCenter': 'Centre d\'aide',
  'landing.contact': 'Contact',
  'landing.faq': 'FAQ',
  'landing.legal': 'Légal',
  'landing.legalNotice': 'Mentions légales',
  'landing.privacyPolicy': 'Politique de confidentialité',
  'landing.terms': 'CGV',
  
  // Payment
  'payment.title': 'Paiement',
  'payment.choosePlan': 'Choisissez votre abonnement',
  'payment.monthly': 'Mensuel',
  'payment.yearly': 'Annuel',
  'payment.perMonth': '/mois',
  'payment.perYear': '/an',
  'payment.savings': 'Économisez 2 mois',
  'payment.subscribe': 'S\'abonner',
  'payment.success': 'Paiement réussi !',
  'payment.thankYou': 'Merci pour votre abonnement',
  
  // Email Modal
  'email.sent': 'Message envoyé !',
  
  // Common
  'common.ok': 'OK',
  'common.cancel': 'Annuler',
  'common.save': 'Enregistrer',
  'common.delete': 'Supprimer',
  'common.edit': 'Modifier',
  'common.close': 'Fermer',
  'common.minimize': 'Réduire',
  'common.maximize': 'Agrandir',
  'common.exitFullscreen': 'Sortie plein écran',
  'common.escapeHint': '← Échap',
  'common.adminMode': 'Mode Administrateur Actif',
  'common.closeAdminSession': 'Fermer la session Admin',
  'common.help': 'Aide',
  'common.goToTop': 'Aller en haut de l\'album',
  'common.goUp25': 'Remonter de 25 photos',
  'common.goDown25': 'Descendre de 25 photos',
  'common.goToEnd': 'Aller à la fin de l\'album',
  'common.closeEsc': 'Fermer (Échap)',
  'common.previousPhoto': 'Photo précédente (←)',
  'common.nextPhoto': 'Photo suivante (→)',
  'common.fullscreen': 'Plein écran (F)',
  'common.playPause': 'Lecture/Pause (Espace)',
  'common.mute': 'Muet (M)',
  'common.previousVideo': 'Vidéo précédente (Shift+←)',
  'common.nextVideo': 'Vidéo suivante (Shift+→)',
  'common.togglePlaylist': 'Afficher/masquer la playlist (L)',
  'common.clickToEdit': 'Cliquez pour modifier les détails',
  'common.comments': 'Commentaires / Métadonnées',
  'common.deletePhoto': 'Supprimer la photo',
  'common.editDetails': 'Modifier les détails',
  'common.sidebar': 'Sidebar',
  'common.background': 'Fond',
  'common.border': 'Bordure',
  'common.categoryPhotos': 'Catégorie pour photos',
  'common.categoryVideos': 'Catégorie pour vidéos',
  'common.categoryDocuments': 'Catégorie pour documents',
  'common.categoryMixed': 'Catégorie mixte (tous types)',
  'common.deleteCategory': 'Supprimer cette catégorie',
  'common.confirm': 'Confirmer',
  'common.yes': 'Oui',
  'common.no': 'Non',
  'common.loading': 'Chargement...',
  'common.error': 'Erreur',
  'common.success': 'Succès',
  'common.warning': 'Attention',
  'common.info': 'Information',
  'common.quit': 'Quitter',
  
  // Toasts
  'toast.themeApplied': 'Thème appliqué avec succès',
  'toast.themeReset': 'Thème réinitialisé',
  'toast.avatarDeleted': 'Avatar supprimé',
  'toast.avatarUpdated': 'Avatar mis à jour ! Rechargez la page pour voir les changements.',
  'toast.settingsSaved': 'Paramètres enregistrés',
  'toast.categoryCreated': 'Catégorie créée',
  'toast.albumCreated': 'Album créé',
  'toast.categoryDeleted': 'Catégorie supprimée',
  'toast.albumRenamed': 'Album renommé',
  'toast.albumDeleted': 'Album supprimé',
  'toast.featureComingSoon': 'Fonctionnalité à venir',
  'toast.categoryUnlocked': 'Catégorie déverrouillée',
  'toast.wrongPassword': 'Mot de passe incorrect',
  'toast.deleteError': 'Erreur lors de la suppression',
  'toast.moveError': 'Erreur lors du déplacement',
  'toast.albumMoved': 'Album déplacé avec succès',
  'toast.selectAlbumFirst': 'Sélectionnez un album',
  'toast.selectAlbumFirstDesc': 'Cliquez sur un album dans la liste pour accéder aux fonctionnalités.',
  'toast.factoryResetComplete': '🏭 Réinitialisation terminée ! L\'application est revenue à zéro.',
  'toast.factoryResetError': 'Erreur lors de la réinitialisation',
  'toast.preparingBackup': 'Préparation de la sauvegarde...',
  'toast.backupDownloaded': 'Sauvegarde téléchargée avec succès !',
  'toast.backupError': 'Erreur lors de la sauvegarde.',
  'toast.unexpectedError': 'Une erreur inattendue est survenue.',
  'toast.imageTooLarge': 'L\'image ne doit pas dépasser 2 Mo',
  'toast.cleanupComplete': 'Nettoyage terminé: {count} catégories supprimées',
  'toast.cleanupError': 'Erreur lors du nettoyage',
  'settings.accessGranted': 'Accès autorisé',
  
  // Utilitaires / Aide (compléments)
  'help.quit': 'Quitter',
  'help.macNote': '(Mac : Cmd au lieu de Ctrl)',
  'help.fileNotAvailable': 'Le fichier n\'est pas encore disponible.',
  'help.comingSoon': 'Fonctionnalité à venir !',
  'help.processingComplete': 'Traitement terminé ! {count} décisions prises.',
  
  // Storage
  'storage.localStorage': 'Stockage local',
  'storage.nearLimit': 'Attention : vous approchez de la limite de stockage',
  'storage.atLimit': 'Limite de stockage atteinte. Supprimez des fichiers pour continuer.',
  'storage.remaining': 'Espace restant',
  'storage.limitReached': 'Limite de stockage atteinte',
  'storage.cannotAdd': 'Impossible d\'ajouter ces fichiers. Espace insuffisant.',
  'storage.wouldExceed': 'Ces fichiers dépasseraient la limite de {size}',
  'storage.privateAlbums': 'Albums privés',
  'storage.usedOf': 'utilisé sur',
  
  // Cloud Storage
  'cloud.choiceSaved': 'Votre choix a été mémorisé dans les paramètres',
  'cloud.preferredService': 'Service cloud préféré',
  'cloud.preferredPlatform': 'Plateforme préférée',
  'cloud.noPreference': 'Aucune préférence',
  
  // Créations / Atelier
  'creations.title': 'Créations',
  'creations.atelier': 'Atelier Créatif',
  'creations.detourage': 'Détourage',
  'creations.collage': 'Collage',
  'creations.effects': 'Effets',
  'creations.layout': 'Mise en page',
  'creations.library': 'Bibliothèque',
  'creations.export': 'Exporter',
  'creations.print': 'Imprimer',
  'creations.mail': '@Mail',
  'creations.save': 'Enregistrer',
  'creations.undo': 'Annuler',
  'creations.redo': 'Rétablir',
  'creations.selectPhoto': 'Sélectionnez une photo',
  'creations.dragDropHere': 'Glissez-déposez une photo ici',
  'creations.orClickToSelect': 'ou cliquez pour sélectionner',
  'creations.aiCutout': 'Détourage IA',
  'creations.manualLasso': 'Lasso manuel',
  'creations.preview': 'Aperçu',
  'creations.addToLibrary': 'Ajouter à la bibliothèque',
  'creations.masks': 'Masques',
  'creations.shapes': 'Formes',
  'creations.borders': 'Bordures',
  'creations.text': 'Texte',
  'creations.rotation': 'Rotation',
  'creations.resize': 'Redimensionner',
  'creations.layers': 'Calques',
  'creations.bringToFront': 'Premier plan',
  'creations.sendToBack': 'Arrière-plan',
  'creations.bringForward': 'Avancer',
  'creations.sendBackward': 'Reculer',
  'creations.align': 'Aligner',
  'creations.alignLeft': 'Aligner à gauche',
  'creations.alignCenter': 'Centrer horizontalement',
  'creations.alignRight': 'Aligner à droite',
  'creations.alignTop': 'Aligner en haut',
  'creations.alignMiddle': 'Centrer verticalement',
  'creations.alignBottom': 'Aligner en bas',
  'creations.distributeH': 'Distribution horizontale',
  'creations.distributeV': 'Distribution verticale',
  'creations.shadow': 'Ombre portée',
  'creations.borderColor': 'Couleur de bordure',
  'creations.borderWidth': 'Épaisseur de bordure',
  'creations.cropInside': 'Recadrage intérieur',
  'creations.zoomLevel': 'Niveau de zoom',
  'creations.positionX': 'Position X',
  'creations.positionY': 'Position Y',
  'creations.customMask': 'Masque personnalisé',
  'creations.importMask': 'Importer un masque (PNG)',
  'creations.circle': 'Cercle',
  'creations.oval': 'Ovale',
  'creations.triangle': 'Triangle',
  'creations.rectangle': 'Rectangle',
  'creations.hexagon': 'Hexagone',
  'creations.star': 'Étoile',
  'creations.diamond': 'Losange',
  'creations.heart': 'Cœur',
  'creations.pentagon': 'Pentagone',
  'creations.drop': 'Goutte',
  'creations.leaf': 'Feuille',
  'creations.none': 'Aucun',
  'creations.canvasSize': 'Taille du canevas',
  'creations.backgroundColor': 'Couleur de fond',
  'creations.transparent': 'Transparent',
  'creations.white': 'Blanc',
  'creations.black': 'Noir',
  'creations.custom': 'Personnalisé',
  'creations.exportPNG': 'Exporter en PNG',
  'creations.exportJPG': 'Exporter en JPG',
  'creations.highQuality': 'Haute qualité',
  'creations.mediumQuality': 'Qualité moyenne',
  'creations.lowQuality': 'Qualité basse',
  'creations.processing': 'Traitement en cours...',
  'creations.cutoutComplete': 'Détourage terminé !',
  'creations.addedToLibrary': 'Ajouté à la bibliothèque',
  'creations.exportComplete': 'Export terminé !',
  'creations.noElements': 'Aucun élément sur le canevas',
  'creations.selectElement': 'Sélectionnez un élément',
  'creations.deleteElement': 'Supprimer l\'élément',
  'creations.duplicateElement': 'Dupliquer l\'élément',
  'creations.lockElement': 'Verrouiller l\'élément',
  'creations.unlockElement': 'Déverrouiller l\'élément',
  'creations.group': 'Grouper',
  'creations.ungroup': 'Dégrouper',
  'creations.flipHorizontal': 'Retourner horizontalement',
  'creations.flipVertical': 'Retourner verticalement',
  
  // PWA
  'pwa.install': 'Installer',
  'pwa.installTitle': 'Installer DuoClass',
  'pwa.installDescription': 'Installez DuoClass sur votre appareil pour un accès rapide et une utilisation hors-ligne.',
  'pwa.desktopInstructions': 'Sur ordinateur (Chrome, Edge)',
  'pwa.desktopSteps': 'Cliquez sur l\'icône d\'installation dans la barre d\'adresse (⊕) ou utilisez le menu ⋮ → "Installer DuoClass"',
  'pwa.mobileInstructions': 'Sur mobile (Android)',
  'pwa.mobileSteps': 'Ouvrez le menu ⋮ et sélectionnez "Ajouter à l\'écran d\'accueil"',
  'pwa.iosTitle': 'Installer sur iPhone/iPad',
  'pwa.iosStep1': 'Appuyez sur le bouton Partager',
  'pwa.iosStep2': 'Faites défiler et appuyez sur "Sur l\'écran d\'accueil"',
  'pwa.iosStep3': 'Appuyez sur "Ajouter" en haut à droite',
  'pwa.iosSuccess': 'DuoClass apparaîtra sur votre écran d\'accueil !',
  'common.understood': 'Compris',

  // Diaporama
  'slideshow.title': 'Diaporama',
  'slideshow.play': 'Lecture',
  'slideshow.pause': 'Pause',
  'slideshow.stop': 'Arrêter',
  'slideshow.previous': 'Précédent',
  'slideshow.next': 'Suivant',
  'slideshow.duration': 'Durée',
  'slideshow.seconds': 'secondes',
  'slideshow.transition': 'Transition',
  'slideshow.fade': 'Fondu',
  'slideshow.slide': 'Glissement',
  'slideshow.zoom': 'Zoom',
  'slideshow.loop': 'Boucle',
  'slideshow.fullscreen': 'Plein écran',
  'slideshow.exitFullscreen': 'Quitter le plein écran',
  'slideshow.noPhotos': 'Aucune photo sélectionnée',
  'slideshow.selectPhotos': 'Sélectionnez des photos pour créer un diaporama',
  
  // Page Mes Licences
  'licenses.title': 'Mes Licences',
  'licenses.subtitle': 'Gérez vos licences DuoClass et vos appareils',
  'licenses.currentDevice': 'Appareil actuel',
  'licenses.activateLicense': 'Activer une licence',
  'licenses.yourLicenses': 'Vos licences',
  'licenses.loading': 'Chargement...',
  'licenses.noLicense': 'Aucune licence',
  'licenses.noLicenseDesc': 'Vous n\'avez pas encore de licence DuoClass.',
  'licenses.activateCode': 'Activer un code',
  'licenses.buyLicense': 'Acheter une licence',
  'licenses.type': 'Type',
  'licenses.lifetime': 'Licence à vie',
  'licenses.createdOn': 'Créée le',
  'licenses.thisDevice': 'Cet appareil',
  'licenses.unknownDevice': 'Appareil inconnu',
  'licenses.activatedOn': 'Activée le',
  'licenses.transfer': 'Transférer',
  'licenses.transfersUsed': 'Transferts utilisés',
  'licenses.expiresOn': 'Expire le',
  'licenses.history': 'Historique',
  'licenses.noHistory': 'Aucun historique',
  'licenses.eventCreated': 'Licence créée',
  'licenses.eventActivated': 'Activée',
  'licenses.eventDeactivated': 'Désactivée',
  'licenses.eventTransferred': 'Transférée',
  'licenses.eventRevoked': 'Révoquée',
  'licenses.eventReactivated': 'Réactivée',
  'licenses.statusActive': 'Active',
  'licenses.statusPending': 'En attente',
  'licenses.statusExpired': 'Expirée',
  'licenses.statusRevoked': 'Révoquée',
  'licenses.statusTransferred': 'Transférée',
  'licenses.activateTitle': 'Activer une licence',
  'licenses.activateDesc': 'Entrez votre code de licence pour l\'activer sur cet appareil.',
  'licenses.licenseCode': 'Code de licence',
  'licenses.targetDevice': 'Appareil cible',
  'licenses.cancel': 'Annuler',
  'licenses.activate': 'Activer',
  'licenses.transferTitle': 'Transférer la licence',
  'licenses.transferDesc': 'Désactivez cette licence pour pouvoir l\'utiliser sur un autre appareil.',
  'licenses.transferWarning': 'Après désactivation, vous devrez réactiver la licence sur le nouvel appareil avec le même code.',
  'licenses.transferLimit': 'Vous avez droit à 3 transferts maximum par licence.',
  'licenses.deactivateAndTransfer': 'Désactiver et transférer',
  'licenses.successActivated': 'Licence activée avec succès !',
  'licenses.successDeactivated': 'Licence désactivée. Vous pouvez maintenant l\'activer sur un autre appareil.',
  'licenses.errorActivation': 'Erreur lors de l\'activation',
  'licenses.errorDeactivation': 'Erreur lors de la désactivation',
  'licenses.enterCode': 'Veuillez entrer un code de licence',
  'licenses.codeCopied': 'Code copié !',
  // Synchronized missing translations
  'settings.addressPlaceholder': 'Votre adresse complète',
  'settings.autoBackupDesc': 'Programmez des sauvegardes régulières',
  'settings.avatar.choose': 'Choisir une image',
  'settings.avatar.delete': 'Supprimer l\'avatar',
  'settings.avatar.findOnPixabay': 'Trouvez votre avatar parfait sur Pixabay',
  'settings.avatar.title': 'Souhaitez-vous avoir un avatar ?',
  'settings.avatar.uploadYour': 'Ou téléchargez votre photo',
  'settings.avatar.useFunction': 'Utiliser la fonction : choisir une image',
  'settings.cgu': 'Conditions Générales d\'Utilisation (CGU)',
  'settings.cleanCategoriesDesc': 'Supprimer les catégories inutilisées',
  'settings.confirmCodePlaceholder': 'Répétez le code',
  'settings.createBackupDesc': 'Téléchargez tous vos albums et réglages',
  'settings.factoryResetDesc': 'Remet l\'application à zéro : supprime toutes les données.',
  'settings.firstNamePlaceholder': 'Votre prénom',
  'settings.name': 'Nom',
  'settings.namePlaceholder': 'Votre nom',
  'settings.needHelpDesc': 'Notre équipe de support est disponible pour vous aider.',
  'settings.newMasterCode': 'Nouveau Code Maître',
  'settings.newMasterCodePlaceholder': 'Minimum 4 caractères',
  'settings.noLogoutTimeRange': 'Plage horaire sans déconnexion (Ex: Bureau)',
  'settings.restoreBackupDesc': 'Importer un fichier de sauvegarde',
  'settings.securityLevel': 'Niveau de sécurité',
  'settings.sessionLogout': 'Session & Déconnexion',
  'settings.startPageAlbums': 'Albums',
  'settings.startPageDesc': 'Choisissez la page qui s\'affiche à l\'ouverture de l\'application :',
  'settings.startPageDiscovery': 'Page Découverte',
  'settings.startPageHome': 'Accueil (Hub)',
  'settings.startPagePhotoclass': 'Photothèque PhotoClass',

  'help.email': 'support@duoclass.fr',
  'toast.renameError': 'Erreur lors du renommage',
  'trial.expired': "Période d'essai expirée",
  'trial.photoLimitReached': 'Limite de photos atteinte',
  'trial.wouldExceedLimit': 'Cette action dépasserait la limite de photos',
};

// Traductions anglaises
const en: Record<string, string> = {
  // Header
  'app.title': 'DuoClass',
  'app.subtitle': 'Master your photos and documents management',
  'header.admin': 'ADMIN',
  'header.avatar': 'Avatar',
  'header.language': 'EN',
  
  // Trial Banner
  'trial.period': 'Trial period',
  'trial.daysRemaining': 'day remaining',
  'trial.daysRemainingPlural': 'days remaining',
  'trial.photosRemaining': 'photos remaining',
  'trial.subscribe': 'Subscribe',
  
  // Toolbar
  'toolbar.display': 'Display',
  'toolbar.normal': 'Normal',
  'toolbar.size': 'Size',
  'toolbar.import': 'Import',
  'toolbar.add': 'Add',
  'toolbar.delete': 'Delete',
  'toolbar.photoEdit': 'Photo Editing',
  'toolbar.convert': 'Convert',
  'toolbar.email': '@Mail',
  'toolbar.print': 'Print',
'toolbar.slideshow': 'Slideshow',
   'toolbar.creations': 'Workshop',
   'toolbar.photoBook': 'Photo Book',
   
   // Sidebar
  'sidebar.discovery': 'Discovery',
  'sidebar.albums': 'Albums',
  'sidebar.privateAlbums': 'Private Albums',
  'sidebar.settings': 'Settings',
  'sidebar.themes': 'Themes\nInterface',
  'sidebar.help': 'Help',
  'sidebar.utilities': 'Utilities',
  
  // Pages
  'page.home': 'Home',
  'page.albums': 'Albums',
  'page.privateAlbums': 'Private Albums',
  'page.settings': 'Settings',
  'page.themes': 'Themes',
  'page.help': 'Help',
  'page.discovery': 'Discovery',
  'page.photoEdit': 'Photo Editing',
  'page.helpDocs': 'Help & Documentation',
  
  // Albums
  'albums.title': 'Albums',
  'albums.photosVideos': 'Photos & Videos',
  'albums.creations': 'Creations',
  'albums.documents': 'Documents',
  'albums.categories': 'Categories',
  'albums.createCategory': 'Create category/album',
  'albums.notClassified': 'NOT CLASSIFIED',
  'albums.notClassifiedAlbums': 'Not classified',
  'albums.deleteCategory': 'Delete this category',
  'albums.deleteAlbum': 'Delete this album',
  'albums.renameAlbum': 'Rename album',
  'albums.enterNewName': 'Enter new name',
  'albums.newName': 'New name',
  'albums.confirmDelete': 'Confirm deletion',
  'albums.cancel': 'Cancel',
  'albums.delete': 'Delete',
  'albums.noCategory': 'No category',
  'albums.noAlbum': 'No album',
  'albums.returnToAlbums': 'Return to Albums',
  'albums.password4digits': 'Password (4 digits)',
  'albums.protectedCategory': 'Protected category',
  'albums.categoryProtectedMsg': 'The category {category} is protected by a password.',
  'albums.confirmDeleteCategory': 'Are you sure you want to delete the category "{category}"?',
  'albums.confirmDeleteAlbum': 'Are you sure you want to delete the album "{album}"?',
  'albums.allAlbumsWillBeDeleted': 'All albums in this category will also be deleted.',
  'albums.dragToMove': 'Drag to move to another category',
  
  // Albums Privés
  'privateAlbums.title': 'Private Albums',
  'privateAlbums.enterMasterCode': 'Enter the Master Code to access private albums',
  'privateAlbums.masterCode': 'Master Code',
  'privateAlbums.masterCodePlaceholder': 'Master Code (e.g.: 000000)',
  'privateAlbums.unlock': 'Unlock',
  'privateAlbums.hidden': 'Hidden',
  
  // PhotoClass / UniversalAlbumPage
  'photoclass.title': 'PhotoClass',
  'photoclass.accessType': 'Access type',
  'photoclass.photos': 'PHOTOS',
  'photoclass.documents': 'DOCUMENTS',
  'photoclass.category': 'Category',
  'photoclass.album': 'Album',
  'photoclass.images': 'Images',
  'photoclass.returnAlbums': 'Return to Albums',
  'photoclass.deleteAlbum': 'Delete album',
  'photoclass.dropPhotosHere': 'Drop your photos here',
  'photoclass.dropDocsHere': 'Drop your documents here',
  'photoclass.framesCreatedAuto': 'Frames will be created automatically',
  'photoclass.goToTop': 'Go to top of album',
  'photoclass.goUp25': 'Go up 25 photos',
  'photoclass.goDown25': 'Go down 25 photos',
  'photoclass.goToEnd': 'Go to end of album',
  'photoclass.notClassified': 'Not classified',
  'photoclass.imageLimitedResolution': 'Image size is limited due to low resolution',
  
  // Frame Management
  'frames.management': 'Frame management',
  'frames.count': 'Number of frames:',
  'frames.addBefore': 'Add BEFORE',
  'frames.addAfter': 'Add AFTER',
  'frames.deleteEmpty': 'Delete all empty frames',
  'frames.deleteThis': 'Delete this frame',
  'frames.confirmDelete': 'Confirm deletion',
  'frames.containsPhoto': 'This frame contains a photo.',
  'frames.containsDoc': 'This frame contains a document.',
  'frames.confirmDeleteQuestion': 'Do you really want to delete this frame?',
  'frames.emptyFrame': 'Empty the frame',
  'frames.confirmEmptyQuestion': 'Do you really want to empty this frame?',
  
  // Details Modal
  'details.photoDetails': 'Photo details',
  'details.docDetails': 'Document details',
  'details.title': 'Title',
  'details.format': 'Format',
  'details.date': 'Date',
  'details.location': 'Location / Origin',
  'details.comments': 'Comments / Notes',
  
  // Export Modal
  'export.allowDownload': 'Your browser will ask you to allow the download. Click "Allow" to continue.',
  'export.whereFiles': 'Where do your files go?',
  'export.toDesktop': 'To have your files go directly to the Desktop, you can change your browser settings:',
  'export.safariSettings': 'Safari: Preferences → General → Download location → Desktop',
  'export.chromeSettings': 'Chrome: Settings → Downloads → Change → Desktop',
  'export.dontShowAgain': 'Don\'t show this message again',
  'export.continue': 'Continue',
  
  // Convert Modal
  'convert.title': 'Convert elements',
  'convert.pdfFormat': 'PDF Format',
  'convert.pdfDesc': 'Merge into a single document',
  'convert.imagesFormat': 'Images Format (ZIP)',
  'convert.imagesDesc': 'Extract as separate files',
  'convert.outputFormat': 'Output format:',
  
  // Import Modal
  'import.title': 'Import files from...',
  'import.camera': 'Camera',
  'import.takePhoto': 'Take a photo',
  'import.fileManager': 'File Manager',
  'import.fileManagerDesc': '',
  'import.windowsLinux': 'Windows / Linux',
  'import.finder': 'Finder',
  'import.macos': 'macOS',
  
  // Camera Modal
  'camera.title': 'Take a photo',
  'camera.capture': 'Capture',
  
  // Delete Album
  'deleteAlbum.title': 'Delete album',
  'deleteAlbum.password': 'Password',
  'deleteAlbum.passwordRequired': 'Password required',
  'deleteAlbum.deleteForever': 'Delete permanently',
  
  // Move Elements
  'move.title': 'Move elements',
  'move.moveElements': 'Move {count} element(s):',
  'move.noOtherAlbum': 'No other album available',
  'move.createFirst': 'First create another album in {type}',
  'move.selectDestination': 'Select destination album:',
  
  // Settings
  'settings.title': 'Settings',
  'settings.general': 'General',
  'settings.personalization': 'Personalization',
  'settings.security': 'Security',
  'settings.backups': 'Backups',
  'settings.infosLicense': 'Info & License',
  'settings.enterMasterCode': 'Please enter your Master Code.',
  'settings.name': 'Name',
  'settings.namePlaceholder': 'Your name',
  'settings.firstName': 'First name',
  'settings.firstNamePlaceholder': 'Your first name',
  'settings.address': 'Address',
  'settings.addressPlaceholder': 'Your full address',
  'settings.email': 'Email',
  'settings.emailPlaceholder': 'your@email.com',
  'settings.phone': 'Phone number',
  'settings.phonePlaceholder': '06...',
  'settings.startPage': 'Start page',
  'settings.startPageDesc': 'Choose the page that opens when the application starts:',
  'settings.startPageHome': 'Home (Hub)',
  'settings.startPagePhotoclass': 'PhotoClass Library',
  'settings.startPageAlbums': 'Albums',
  'settings.startPageDiscovery': 'Discovery Page',
  'settings.avatar.title': 'Would you like to have an avatar?',
  'settings.avatar.choose': 'Choose an image',
  'settings.avatar.findOnPixabay': 'Find your perfect avatar on Pixabay',
  'settings.avatar.uploadYour': 'Or upload your photo',
  'settings.avatar.useFunction': 'Use the function: choose an image',
  'settings.avatar.delete': 'Delete avatar',
  'settings.wantAvatar': 'Would you like to have an avatar?',
  'settings.chooseImage': 'Choose an image',
  'settings.findAvatarPixabay': 'Find your perfect avatar on Pixabay',
  'settings.orUploadPhoto': 'Or upload your photo',
  'settings.useChooseImage': 'Use the function: choose an image',
  'settings.removeAvatar': 'Remove avatar',
  'settings.newMasterCode': 'New Master Code',
  'settings.newMasterCodePlaceholder': 'Minimum 4 characters',
  'settings.confirmCode': 'Confirm code',
  'settings.confirmCodePlaceholder': 'Repeat the code',
  'settings.sessionLogout': 'Session & Logout',
  'settings.inactivityDelay': 'Inactivity delay (minutes)',
  'settings.noLogoutTimeRange': 'Time range without logout (e.g.: Office)',
  'settings.to': 'to',
  'settings.securityLevel': 'Security level',
  'settings.disabled': 'Disabled',
  'settings.moderate': 'Moderate',
  'settings.strict': 'Strict',
  'settings.veryStrict': 'Very Strict (Level 5)',
  'settings.createBackup': 'Create a backup',
  'settings.createBackupDesc': 'Download all your albums and settings',
  'settings.restoreBackup': 'Restore a backup',
  'settings.restoreBackupDesc': 'Import a backup file',
  'settings.autoBackup': 'Automatic backup',
  'settings.autoBackupDesc': 'Schedule regular backups',
  'settings.cleanCategories': 'Clean categories',
  'settings.cleanCategoriesDesc': 'Delete unused categories',
  'settings.factoryReset': 'Factory reset',
  'settings.factoryResetDesc': 'Resets the application to zero: deletes all data.',
  'settings.cgu': 'Terms of Use',
  'settings.legalNotice': 'Legal Notice',
  'settings.privacyPolicy': 'Privacy Policy',
  'settings.perpetualLicense': 'Perpetual License (Lifetime)',
  'settings.needHelp': 'Need help?',
  'settings.needHelpDesc': 'Our support team is available to help you.',
  'settings.myLicenses': 'My Licenses',
  'settings.myLicensesDesc': 'Manage your DuoClass licenses, activate new codes and transfer licenses between devices.',
  'settings.manageLicenses': 'Manage my licenses',
  'settings.file': 'File:',
  'settings.backupDate': 'Backup date:',
  'settings.albumsCount': 'Albums:',
  'settings.categoriesCount': 'Categories:',
  'settings.settingsIncluded': 'Settings:',
  'settings.importMode': 'Import mode:',
  'settings.merge': 'Merge',
  'settings.replace': 'Replace',
  'settings.replaceWarning': 'Warning: "Replace" mode will delete all your current albums and categories before importing the backup. This action is irreversible.',
  'settings.allDataDeleted': 'All data will be deleted:',
  'settings.allCategories': 'All categories',
  'settings.allAlbums': 'All albums',
  'settings.allPhotosAndDocs': 'All photos and documents',
  'settings.allCustomSettings': 'All custom settings',
  'settings.appResetToInitial': 'The application will return to its initial state (like first launch).',
  'settings.typeToConfirm': 'To confirm, type',
  'settings.resetKeyword': 'RESET',
  'settings.typeResetPlaceholder': 'Type RESET',
  'settings.restrictedAccess': 'Restricted Access',
  'settings.sectionReserved': 'This section is reserved for the administrator.',
  'settings.masterCodeDesc': 'This code protects access to this Administration page, secured albums and sensitive functions.',
  'settings.verifyBeforeImport': 'Verify file information before proceeding with import.',
  'settings.mergeDesc': 'Adds new albums without overwriting existing ones',
  'settings.replaceDesc': 'Deletes everything and restores from backup',
  'settings.importing': 'Importing...',
  'settings.replaceAll': 'Replace all',
  'settings.warningIrreversible': 'WARNING: This action is irreversible!',
  'settings.resetting': 'Resetting...',
  'settings.confirmReset': 'Confirm reset',
  
  // Themes
  'themes.title': 'Interface Themes',
  'themes.reset': 'Reset',
  'themes.apply': 'Apply',
  'themes.colors': 'Colors',
  'themes.texture': 'Outer texture',
  'themes.workarea': 'Work area background',
  'themes.saveConfig': 'Save current configuration',
  'themes.configNamePlaceholder': 'Configuration name (e.g.: My office theme)',
  'themes.mySavedConfigs': 'My saved configurations',
  'themes.classic': 'Classic',
  'themes.starryNight': 'Starry Night',
  'themes.nordic': 'Nordic',
  'themes.forest': 'Forest',
  'themes.ocean': 'Ocean',
  'themes.sunset': 'Sunset',
  'themes.lavender': 'Lavender',
  'themes.graphite': 'Graphite',
  'themes.rose': 'Rose',
  'themes.midnightGold': 'Midnight Gold',
  'themes.none': 'None',
  'themes.brownLeather': 'Brown Leather',
  'themes.crocoLeather': 'Croco Leather',
  'themes.moireBlue': 'Blue Moiré',
  'themes.moireGreen': 'Green Moiré',
  'themes.moireRed': 'Red Moiré',
  'themes.moirePink': 'Pink Moiré',
  'themes.marbleBlue': 'Blue Marble',
  'themes.marbleBeige': 'Beige Marble',
  'themes.rustedMetal': 'Rusted Metal',
  'themes.gold': 'Gold',
  'themes.bamboo': 'Bamboo',
  'themes.flames': 'Flames',
  'themes.transparent': 'Transparent',
  'themes.white': 'White',
  'themes.sand': 'Sand',
  'themes.cream': 'Cream',
  'themes.ivory': 'Ivory',
  'themes.pastelBlue': 'Blue',
  'themes.pastelGreen': 'Green',
  'themes.pastelPink': 'Pink',
  'themes.pastelLavender': 'Lavender',
  'themes.pastelPeach': 'Peach',
  'themes.gray': 'Gray',
  'themes.myConfigs': 'My configurations',
  'themes.save': 'Save',
  'themes.applyConfig': 'Apply',
  'themes.noConfigs': 'No saved configuration. Customize your theme then click "Save this configuration".',
  'themes.currentConfig': 'Current configuration',
  'themes.enterConfigName': 'Please enter a name for this configuration',
  'themes.configSaved': 'Configuration saved!',
  'themes.configApplied': 'Configuration applied!',
  'themes.configDeleted': 'Configuration deleted',
  
  // Retouche Photo
  'photoEdit.title': 'Photo Editing',
  'photoEdit.originalPhoto': 'Original photo',
  'photoEdit.editedPhoto': 'Edited photo',
  'photoEdit.noPhoto': 'No photo',
  'photoEdit.doubleClickZoom': 'Double-click to enlarge',
  'photoEdit.titlePlaceholder': 'Title',
  'photoEdit.commentsPlaceholder': 'Comments',
  'photoEdit.selectedInPhotoclass': 'Photo selected in PhotoClass',
  'photoEdit.editedWillAppear': 'The edited photo will appear here',
  'photoEdit.newEdit': 'New edit',
  'photoEdit.saveAsCopy': 'Save as copy in album',
  
  // Help / Utilitaires
  'help.title': 'Help',
  'help.docCenter': 'Documentation Center',
  'help.techSupport': 'Technical support:',
  'help.adminInfosLicense': 'Administration > Info & License',
  'help.didYouKnow': 'Did you know?',
  'help.contextualHelp': 'Access contextual help by clicking the "Thumb" button 👍 in the top bar.',
  'help.welcome': 'Welcome to DuoClass Help',
  'help.description': 'DuoClass is your photo and document management application.',
  'help.duplicateValidation': 'Duplicate Validation',
  'help.duplicateDesc': 'Manage photos detected as duplicates.',
  'help.manage': 'Manage',
  'help.quickStart': 'Quick Start Guide',
  'help.quickStartDesc': 'The essentials to get started.',
  'help.view': 'View',
  'help.userManual': 'User Manual',
  'help.userManualDesc': 'All features (PDF).',
  'help.read': 'Read',
  'help.shortcuts': 'Keyboard Shortcuts',
  'help.shortcutsDesc': 'All shortcuts to go faster.',
  'help.techSupportTitle': 'Technical Support',
  'help.techSupportDesc': 'Contact our team.',
  
  // WorkSpace
  'workspace.title': 'Workspace',
  'workspace.emptyZone': 'Empty workspace',
  'workspace.dragItems': 'Drag items here or use the toolbar',
  
  // Home / Landing
  'home.adminMode': 'Warning, you are in "Administrator" mode, don\'t forget to return to free mode',
  'home.confirmQuit': 'Are you sure you want to quit?',
  'home.secureAlbum': 'Secure Album',
  'home.enterMasterCode': 'Please enter your Master Code to access this album.',
  'home.validate': 'Validate',
  'home.deleteAlbum': 'Delete album',
  'home.masterCodeRequired': 'Master Code required:',
  
  // Landing Page
  'landing.title': 'DuoClass',
  'landing.subtitle': 'Master your photos and documents management',
  'landing.startFree': 'Start for free',
  'landing.login': 'Log in',
  'landing.freeTrial': 'Free trial',
  'landing.intuitiveInterface': 'An intuitive interface',
  'landing.discoverApp': 'Discover the DuoClass application in action',
  'landing.organizeMedia': 'Organize your media',
  'landing.classifyDocs': 'Classify your papers',
  'landing.secure': 'Secure',
  'landing.privateAlbums': 'Private albums',
  'landing.product': 'Product',
  'landing.features': 'Features',
  'landing.pricing': 'Pricing',
  'landing.updates': 'Updates',
  'landing.support': 'Support',
  'landing.helpCenter': 'Help Center',
  'landing.contact': 'Contact',
  'landing.faq': 'FAQ',
  'landing.legal': 'Legal',
  'landing.legalNotice': 'Legal Notice',
  'landing.privacyPolicy': 'Privacy Policy',
  'landing.terms': 'Terms',
  
  // Payment
  'payment.title': 'Payment',
  'payment.choosePlan': 'Choose your subscription',
  'payment.monthly': 'Monthly',
  'payment.yearly': 'Yearly',
  'payment.perMonth': '/month',
  'payment.perYear': '/year',
  'payment.savings': 'Save 2 months',
  'payment.subscribe': 'Subscribe',
  'payment.success': 'Payment successful!',
  'payment.thankYou': 'Thank you for your subscription',
  
  // Email Modal
  'email.sent': 'Message sent!',
  
  // Common
  'common.ok': 'OK',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.close': 'Close',
  'common.minimize': 'Minimize',
  'common.maximize': 'Maximize',
  'common.exitFullscreen': 'Exit fullscreen',
  'common.escapeHint': '← Esc',
  'common.adminMode': 'Admin Mode Active',
  'common.closeAdminSession': 'Close Admin Session',
  'common.help': 'Help',
  'common.goToTop': 'Go to top of album',
  'common.goUp25': 'Go up 25 photos',
  'common.goDown25': 'Go down 25 photos',
  'common.goToEnd': 'Go to end of album',
  'common.closeEsc': 'Close (Esc)',
  'common.previousPhoto': 'Previous photo (←)',
  'common.nextPhoto': 'Next photo (→)',
  'common.fullscreen': 'Fullscreen (F)',
  'common.playPause': 'Play/Pause (Space)',
  'common.mute': 'Mute (M)',
  'common.previousVideo': 'Previous video (Shift+←)',
  'common.nextVideo': 'Next video (Shift+→)',
  'common.togglePlaylist': 'Show/hide playlist (L)',
  'common.clickToEdit': 'Click to edit details',
  'common.comments': 'Comments / Metadata',
  'common.deletePhoto': 'Delete photo',
  'common.editDetails': 'Edit details',
  'common.sidebar': 'Sidebar',
  'common.background': 'Background',
  'common.border': 'Border',
  'common.categoryPhotos': 'Category for photos',
  'common.categoryVideos': 'Category for videos',
  'common.categoryDocuments': 'Category for documents',
  'common.categoryMixed': 'Mixed category (all types)',
  'common.deleteCategory': 'Delete this category',
  'common.confirm': 'Confirm',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.loading': 'Loading...',
  'common.error': 'Error',
  'common.success': 'Success',
  'common.warning': 'Warning',
  'common.info': 'Information',
  'common.quit': 'Quit',
  
  // Toasts
  'toast.themeApplied': 'Theme applied successfully',
  'toast.themeReset': 'Theme reset',
  'toast.avatarDeleted': 'Avatar deleted',
  'toast.avatarUpdated': 'Avatar updated',
  'toast.settingsSaved': 'Settings saved',
  'toast.categoryCreated': 'Category created',
  'toast.albumCreated': 'Album created',
  'toast.categoryDeleted': 'Category deleted',
  'toast.albumRenamed': 'Album renamed',
  'toast.albumDeleted': 'Album deleted',
  'toast.featureComingSoon': 'Feature coming soon',
  'toast.categoryUnlocked': 'Category unlocked',
  'toast.wrongPassword': 'Wrong password',
  'toast.deleteError': 'Error during deletion',
  'toast.moveError': 'Error during move',
  'toast.albumMoved': 'Album moved successfully',
  'toast.selectAlbumFirst': 'Select an album',
  'toast.selectAlbumFirstDesc': 'Click on an album in the list to access features.',
  'toast.factoryResetComplete': '🏭 Factory reset complete! The application has been reset to zero.',
  'toast.factoryResetError': 'Error during factory reset',
  'toast.preparingBackup': 'Preparing backup...',
  'toast.backupDownloaded': 'Backup downloaded successfully!',
  'toast.backupError': 'Error during backup.',
  'toast.unexpectedError': 'An unexpected error occurred.',
  'toast.imageTooLarge': 'Image must not exceed 2 MB',
  'toast.cleanupComplete': 'Cleanup complete: {count} categories deleted',
  'toast.cleanupError': 'Error during cleanup',
  'settings.accessGranted': 'Access granted',
  
  // Help (complements)
  'help.quit': 'Quit',
  'help.macNote': '(Mac: Cmd instead of Ctrl)',
  'help.fileNotAvailable': 'File not yet available.',
  'help.comingSoon': 'Feature coming soon!',
  'help.processingComplete': 'Processing complete! {count} decisions made.',
  
  // Storage
  'storage.localStorage': 'Local storage',
  'storage.nearLimit': 'Warning: you are approaching the storage limit',
  'storage.atLimit': 'Storage limit reached. Delete files to continue.',
  'storage.remaining': 'Remaining space',
  'storage.limitReached': 'Storage limit reached',
  'storage.cannotAdd': 'Cannot add these files. Insufficient space.',
  'storage.wouldExceed': 'These files would exceed the {size} limit',
  'storage.privateAlbums': 'Private albums',
  'storage.usedOf': 'used of',
  
  // Cloud Storage
  'cloud.choiceSaved': 'Your choice has been saved in settings',
  'cloud.preferredService': 'Preferred cloud service',
  'cloud.preferredPlatform': 'Preferred platform',
  'cloud.noPreference': 'No preference',
  
  // Creations / Workshop
  'creations.title': 'Creations',
  'creations.atelier': 'Creative Workshop',
  'creations.detourage': 'Cutout',
  'creations.collage': 'Collage',
  'creations.effects': 'Effects',
  'creations.layout': 'Layout',
  'creations.library': 'Library',
  'creations.export': 'Export',
  'creations.print': 'Print',
  'creations.mail': '@Mail',
  'creations.save': 'Save',
  'creations.undo': 'Undo',
  'creations.redo': 'Redo',
  'creations.selectPhoto': 'Select a photo',
  'creations.dragDropHere': 'Drag and drop a photo here',
  'creations.orClickToSelect': 'or click to select',
  'creations.aiCutout': 'AI Cutout',
  'creations.manualLasso': 'Manual Lasso',
  'creations.preview': 'Preview',
  'creations.addToLibrary': 'Add to library',
  'creations.masks': 'Masks',
  'creations.shapes': 'Shapes',
  'creations.borders': 'Borders',
  'creations.text': 'Text',
  'creations.rotation': 'Rotation',
  'creations.resize': 'Resize',
  'creations.layers': 'Layers',
  'creations.bringToFront': 'Bring to front',
  'creations.sendToBack': 'Send to back',
  'creations.bringForward': 'Bring forward',
  'creations.sendBackward': 'Send backward',
  'creations.align': 'Align',
  'creations.alignLeft': 'Align left',
  'creations.alignCenter': 'Center horizontally',
  'creations.alignRight': 'Align right',
  'creations.alignTop': 'Align top',
  'creations.alignMiddle': 'Center vertically',
  'creations.alignBottom': 'Align bottom',
  'creations.distributeH': 'Distribute horizontally',
  'creations.distributeV': 'Distribute vertically',
  'creations.shadow': 'Drop shadow',
  'creations.borderColor': 'Border color',
  'creations.borderWidth': 'Border width',
  'creations.cropInside': 'Crop inside',
  'creations.zoomLevel': 'Zoom level',
  'creations.positionX': 'Position X',
  'creations.positionY': 'Position Y',
  'creations.customMask': 'Custom mask',
  'creations.importMask': 'Import mask (PNG)',
  'creations.circle': 'Circle',
  'creations.oval': 'Oval',
  'creations.triangle': 'Triangle',
  'creations.rectangle': 'Rectangle',
  'creations.hexagon': 'Hexagon',
  'creations.star': 'Star',
  'creations.diamond': 'Diamond',
  'creations.heart': 'Heart',
  'creations.pentagon': 'Pentagon',
  'creations.drop': 'Drop',
  'creations.leaf': 'Leaf',
  'creations.none': 'None',
  'creations.canvasSize': 'Canvas size',
  'creations.backgroundColor': 'Background color',
  'creations.transparent': 'Transparent',
  'creations.white': 'White',
  'creations.black': 'Black',
  'creations.custom': 'Custom',
  'creations.exportPNG': 'Export as PNG',
  'creations.exportJPG': 'Export as JPG',
  'creations.highQuality': 'High quality',
  'creations.mediumQuality': 'Medium quality',
  'creations.lowQuality': 'Low quality',
  'creations.processing': 'Processing...',
  'creations.cutoutComplete': 'Cutout complete!',
  'creations.addedToLibrary': 'Added to library',
  'creations.exportComplete': 'Export complete!',
  'creations.noElements': 'No elements on canvas',
  'creations.selectElement': 'Select an element',
  'creations.deleteElement': 'Delete element',
  'creations.duplicateElement': 'Duplicate element',
  'creations.lockElement': 'Lock element',
  'creations.unlockElement': 'Unlock element',
  'creations.group': 'Group',
  'creations.ungroup': 'Ungroup',
  'creations.flipHorizontal': 'Flip horizontally',
  'creations.flipVertical': 'Flip vertically',
  
  // PWA
  'pwa.install': 'Install',
  'pwa.installTitle': 'Install DuoClass',
  'pwa.installDescription': 'Install DuoClass on your device for quick access and offline use.',
  'pwa.desktopInstructions': 'On desktop (Chrome, Edge)',
  'pwa.desktopSteps': 'Click the install icon in the address bar (⊕) or use the menu ⋮ → "Install DuoClass"',
  'pwa.mobileInstructions': 'On mobile (Android)',
  'pwa.mobileSteps': 'Open the menu ⋮ and select "Add to Home Screen"',
  'pwa.iosTitle': 'Install on iPhone/iPad',
  'pwa.iosStep1': 'Tap the Share button',
  'pwa.iosStep2': 'Scroll down and tap "Add to Home Screen"',
  'pwa.iosStep3': 'Tap "Add" in the top right',
  'pwa.iosSuccess': 'DuoClass will appear on your home screen!',
  'common.understood': 'Got it',

  // Slideshow
  'slideshow.title': 'Slideshow',
  'slideshow.play': 'Play',
  'slideshow.pause': 'Pause',
  'slideshow.stop': 'Stop',
  'slideshow.previous': 'Previous',
  'slideshow.next': 'Next',
  'slideshow.duration': 'Duration',
  'slideshow.seconds': 'seconds',
  'slideshow.transition': 'Transition',
  'slideshow.fade': 'Fade',
  'slideshow.slide': 'Slide',
  'slideshow.zoom': 'Zoom',
  'slideshow.loop': 'Loop',
  'slideshow.fullscreen': 'Fullscreen',
  'slideshow.exitFullscreen': 'Exit fullscreen',
  'slideshow.noPhotos': 'No photos selected',
  'slideshow.selectPhotos': 'Select photos to create a slideshow',
  
  // Page My Licenses
  'licenses.title': 'My Licenses',
  'licenses.subtitle': 'Manage your DuoClass licenses and devices',
  'licenses.currentDevice': 'Current device',
  'licenses.activateLicense': 'Activate a license',
  'licenses.yourLicenses': 'Your licenses',
  'licenses.loading': 'Loading...',
  'licenses.noLicense': 'No license',
  'licenses.noLicenseDesc': 'You don\'t have a DuoClass license yet.',
  'licenses.activateCode': 'Activate a code',
  'licenses.buyLicense': 'Buy a license',
  'licenses.type': 'Type',
  'licenses.lifetime': 'Lifetime license',
  'licenses.createdOn': 'Created on',
  'licenses.thisDevice': 'This device',
  'licenses.unknownDevice': 'Unknown device',
  'licenses.activatedOn': 'Activated on',
  'licenses.transfer': 'Transfer',
  'licenses.transfersUsed': 'Transfers used',
  'licenses.expiresOn': 'Expires on',
  'licenses.history': 'History',
  'licenses.noHistory': 'No history',
  'licenses.eventCreated': 'License created',
  'licenses.eventActivated': 'Activated',
  'licenses.eventDeactivated': 'Deactivated',
  'licenses.eventTransferred': 'Transferred',
  'licenses.eventRevoked': 'Revoked',
  'licenses.eventReactivated': 'Reactivated',
  'licenses.statusActive': 'Active',
  'licenses.statusPending': 'Pending',
  'licenses.statusExpired': 'Expired',
  'licenses.statusRevoked': 'Revoked',
  'licenses.statusTransferred': 'Transferred',
  'licenses.activateTitle': 'Activate a license',
  'licenses.activateDesc': 'Enter your license code to activate it on this device.',
  'licenses.licenseCode': 'License code',
  'licenses.targetDevice': 'Target device',
  'licenses.cancel': 'Cancel',
  'licenses.activate': 'Activate',
  'licenses.transferTitle': 'Transfer license',
  'licenses.transferDesc': 'Deactivate this license to use it on another device.',
  'licenses.transferWarning': 'After deactivation, you will need to reactivate the license on the new device with the same code.',
  'licenses.transferLimit': 'You have a maximum of 3 transfers per license.',
  'licenses.deactivateAndTransfer': 'Deactivate and transfer',
  'licenses.successActivated': 'License activated successfully!',
  'licenses.successDeactivated': 'License deactivated. You can now activate it on another device.',
  'licenses.errorActivation': 'Error during activation',
  'licenses.errorDeactivation': 'Error during deactivation',
  'licenses.enterCode': 'Please enter a license code',
  'licenses.codeCopied': 'Code copied!',
  // Synchronized missing translations
  'settings.accessDenied': 'Access granted',
  'settings.aiAnalysis': 'Artificial Intelligence automatically analyzes and blocks sensitive content during import.',
  'settings.backupRecovery': 'Backup & Recovery',
  'settings.chooseStartPage': 'Choose the page that opens when the application starts:',
  'settings.clean': 'Clean',
  'settings.contactSupport': 'Contact technical support',
  'settings.currentCode': 'Current code',
  'settings.currentLevel': 'Current level',
  'settings.day': 'Day',
  'settings.deleteUnused': 'Delete unused categories',
  'settings.discovery': 'Discovery Page',
  'settings.download': 'Download',
  'settings.downloadAlbums': 'Download all your albums and settings',
  'settings.home': 'Home (Hub)',
  'settings.hour': 'hour',
  'settings.import': 'Import',
  'settings.importBackupFile': 'Import a backup file',
  'settings.irreversible': 'Irreversible!',
  'settings.lastName': 'Last name',
  'settings.legalInfo': 'Legal Information & Support',
  'settings.level5Desc': 'Level 5 blocks all nudity, violence or inappropriate content with zero tolerance.',
  'settings.masterCode': 'Master Code',
  'settings.masterCodePlaceholder': 'Master code...',
  'settings.min4chars': 'Minimum 4 characters',
  'settings.minutes': 'minutes',
  'settings.month': 'Month',
  'settings.newCode': 'New code',
  'settings.noDisconnectTimeRange': 'Time range without logout (e.g.: Office)',
  'settings.parentalControl': 'Parental Control',
  'settings.personalInfo': 'Personal Information',
  'settings.photoLibrary': 'PhotoClass Library',
  'settings.protectedAccess': 'Protected Access',
  'settings.recommended': 'Recommended',
  'settings.repeatCode': 'Repeat the code',
  'settings.reset': 'Reset',
  'settings.resetDesc': 'Resets the application to zero: deletes all data.',
  'settings.saveSessionSettings': 'Save session settings',
  'settings.scheduleBackups': 'Schedule regular backups',
  'settings.sessionDisconnect': 'Session & Logout',
  'settings.supportAvailable': 'Our support team is available to help you.',
  'settings.termsOfUse': 'Terms of Use',
  'settings.updateCode': 'Update code',
  'settings.week': 'Week',
  'settings.wrongCode': 'Wrong code',
  'settings.yourAddress': 'Your full address',
  'settings.yourFirstName': 'Your first name',
  'settings.yourLastName': 'Your last name',

};

const translations: Record<Language, Record<string, string>> = { fr, en };

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('duoclass_language');
    return (saved as Language) || 'fr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('duoclass_language', lang);
    // Dispatch event pour mettre à jour les autres composants
    window.dispatchEvent(new Event('languageChanged'));
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };
  useEffect(() => {
    const handleLanguageChange = () => {
      const saved = localStorage.getItem('duoclass_language');
      if (saved && saved !== language) {
        setLanguageState(saved as Language);
      }
    };
    
    window.addEventListener('languageChanged', handleLanguageChange);
    return () => window.removeEventListener('languageChanged', handleLanguageChange);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export { fr, en, translations };
